title: Services

pages:
  template: service
  sort:     title asc

deletable: false

files:
  type: image
  sortable: true

fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  seo_summary:
    label: SEO Summary
    type: textarea
    buttons: false